app/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^$", views.events, name="events"),
    # re_path(r'^old/$', views.events_old, name='old-events'),
    re_path(r"^new/$", views.event_new, name="new-event"),
    re_path(r"^(\d+)/$", views.event_show, name="event-show"),
    re_path(r"^(\d+)/edit/$", views.event_edit, name="event-edit"),
    re_path(r"^(\d+)/destroy/$", views.event_destroy, name="event-destroy"),
    # re_path(r'^(\d+)/download/$', views.event_download, name='event-download'),
    re_path(r"^funders/(\d+)/edit/$", views.funder_edit, name="funder-edit"),
    re_path(r"^export-requests/$", views.export_requests, name="export-requests"),
    re_path(r"^health/", views.HealthView.as_view(), name="health"),
]

penncfa/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.urls import include, re_path
from django_registration.backends.activation.views import RegistrationView

from app.forms import (
    PasswordChangeForm,
    PasswordResetForm,
    RegistrationForm,
    SetPasswordForm,
)


admin.autodiscover()

admin.site.site_header = "CFA administration"

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(
        r"^accounts/password/change/$",
        PasswordChangeView.as_view(form_class=PasswordChangeForm),
        name="auth_password_change",
    ),
    re_path(
        r"^accounts/password/reset/$",
        PasswordResetView.as_view(form_class=PasswordResetForm),
        name="auth_password_reset",
    ),
    re_path(
        r"^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        PasswordResetConfirmView.as_view(form_class=SetPasswordForm),
        name="password_reset_confirm",
    ),
    re_path(
        r"^accounts/password/reset/complete/$",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    re_path(
        r"^accounts/register/$",
        RegistrationView.as_view(form_class=RegistrationForm),
        name="registration_register",
    ),
    re_path(r"^accounts/", include("django_registration.backends.activation.urls")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"", include("app.urls")),
]

app/models.py
import datetime
from hashlib import sha1

from django.conf import settings
from django.contrib.auth.models import User
from django.core import mail
from django.core.mail import EmailMessage
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.urls import reverse


YES_OR_NO = (
    ("Y", "YES"),
    ("N", "NO"),
)

REQUESTER_OR_FUNDER = (
    ("R", "REQUESTER"),
    ("F", "FUNDER"),
)


def can_send_email():
    """Only actually send the emails if not in DEBUG mode or if testing

    To check if in testing, we see if mail has an outbox, which is part of
    Django's testing tools.
    """
    return not settings.DEBUG or hasattr(mail, "outbox")


class CFAUser(models.Model):
    """
    A CFA User profile.
    # Create user
    >>> u = User.objects.create_user("alice", "alice@example.com", "1234")
    >>> cfau = u.profile
    >>> cfau.is_requester
    True
    """

    funder_name = models.CharField(max_length=256, default="", blank=True)
    user = models.OneToOneField(
        User,
        help_text="You must first create a user before adding them to the CFA.",
        related_name="profile",
        on_delete=models.CASCADE,
    )
    user_type = models.CharField(max_length=1, choices=REQUESTER_OR_FUNDER)
    phone = models.CharField(max_length=15)
    # The e-mail of the contact in OSA
    osa_email = models.EmailField(
        "OSA Contact Email",
        null=True,
        help_text="The email address for contacting OSA when an app is funded.",
        blank=True,
    )
    cc_emails = models.ManyToManyField("CCEmail", blank=True)
    mission_statement = models.TextField(blank=True)
    email_template = models.TextField(blank=True)
    email_subject = models.TextField(blank=True)
    send_email_template = models.BooleanField(default=False)

    def __str__(self):
        if self.is_funder:
            # some funders might not have funder_names
            return str(self.funder_name) or str(self.user)
        else:
            return str(self.user)

    @property
    def is_funder(self):
        return self.user_type == "F"

    @property
    def is_requester(self):
        return not self.is_funder

    def requested(self, event):
        """Check if a user requested an event."""
        assert self.is_requester
        return self == event.requester

    def notify_osa(self, event, grants):
        """Notify OSA that an event has been funded."""
        assert self.is_funder
        context = {"funder": self, "event": event, "grants": grants}
        subject = render_to_string("app/osa_email_subject.txt", context=context).strip()
        message = render_to_string("app/osa_email.txt", context=context)
        recipients = [str(self.osa_email)]
        headers = {"Reply-To": self.user.email}
        email = EmailMessage(
            subject, message, settings.DEFAULT_FROM_EMAIL, recipients, headers
        )
        if can_send_email():
            email.send()

    def required_eligibility_question_ids(self):
        question_ids = self.funderconstraint_set.values_list("question_id", flat=True)
        return ",".join(str(id) for id in question_ids)

    class Meta:
        verbose_name = "CFA Users"
        verbose_name_plural = "CFA Users"


@receiver(sender=User, signal=post_save)
def create_profile(sender, instance, signal, created, raw, **kwargs):
    """Create a CFAUser whenever a user is created."""
    if created and not raw:
        CFAUser.objects.create(user=instance, user_type="R")


class Event(models.Model):
    STATUS = (
        ("S", "SAVED"),
        ("B", "SUBMITTED"),
        ("F", "FUNDED"),
        ("W", "FOLLOWUP"),
        ("O", "OVER"),
    )
    """An Event object."""
    name = models.CharField(max_length=256)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=256)
    requester = models.ForeignKey(
        CFAUser, related_name="event_requester", on_delete=models.SET_NULL, null=True
    )
    contact_name = models.CharField(max_length=256, blank=True)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=15)
    anticipated_attendance = models.IntegerField()
    advisor_email = models.EmailField(blank=True)
    advisor_phone = models.CharField(max_length=15, blank=True)
    organizations = models.CharField(max_length=256)
    applied_funders = models.ManyToManyField(
        CFAUser, related_name="event_applied_funders"
    )
    funding_already_received = models.DecimalField(
        max_digits=17, decimal_places=2, default=0
    )
    status = models.CharField(max_length=1, choices=STATUS)
    created_at = models.DateTimeField(default=datetime.datetime.now)
    updated_at = models.DateTimeField(default=datetime.datetime.now)

    def save(self, *args, **kwargs):
        self.updated_at = datetime.datetime.now()
        return super(Event, self).save(*args, **kwargs)

    @property
    def has_update(self):
        return abs((self.updated_at - self.created_at).seconds) > 60 * 60

    @property
    def over(self):
        return self.status == "O"

    @property
    def saved(self):
        return self.status == "S"

    @property
    def followup_needed(self):
        return self.status == "W"

    @property
    def submitted(self):
        return self.status == "B"

    @property
    def locked(self):
        return self.funded or self.over
        # return self.submitted or self.funded or self.over

    @property
    def total_funds_already_received(self):
        """
        The total amount of money already received
        (before grants) for an event.
        """
        return self.funding_already_received + sum(
            item.funding_already_received for item in self.item_set.all()
        )

    @property
    def amounts(self):
        """Get a dictionary containing the amount each funder has granted."""
        amounts = dict((funder, None) for funder in self.applied_funders.all())
        for item in self.item_set.all():
            for grant in item.grant_set.all():
                if grant.funder not in amounts or amounts[grant.funder] is None:
                    amounts[grant.funder] = grant.amount
                else:
                    amounts[grant.funder] += grant.amount
        return amounts

    @property
    def total_funds_granted(self):
        """The total amount of money received via grants."""
        sum = 0
        for val in self.amounts.values():
            sum = sum + val if val is not None else sum
        return sum

    @property
    def funded(self):
        """Whether or not an event has been funded."""
        return self.status == "F"

    @property
    def total_funds_received(self):
        """The total amount of money received (grants + pre grant)."""
        return self.total_funds_already_received + self.total_funds_granted

    @property
    def total_expense(self):
        """The total amount of money requested for an event."""
        return sum(item.total for item in self.item_set.all() if not item.revenue)

    @property
    def total_additional_funds(self):
        """The tatal amount of non-CFA funding and admission fees."""
        return sum(item.total for item in self.item_set.all() if item.revenue)

    @property
    def total_remaining(self):
        return (
            self.total_expense - self.total_funds_received - self.total_additional_funds
        )

    @property
    def date_passed(self):
        return datetime.date.today() > self.date + datetime.timedelta(days=14)

    @property
    def comments(self):
        return self.comment_set.order_by("created")

    def notify_funders(self, new=False):
        """Notify all the funders of an event that they have been applied to"""
        context = {"requester": self.requester, "event": self}

        template = "app/application_email" if new else "app/application_changed"

        subject = render_to_string("%s_subject.txt" % template, context=context).strip()
        message = render_to_string("%s.txt" % template, context=context)

        for funder in self.applied_funders.all():
            self.notify_funder(subject, message, funder)

    def notify_funder(self, subject, message, funder):
        """Notify a funder that the requester has applied to them."""
        assert funder.is_funder
        email = EmailMessage(
            subject=subject,
            body=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[funder.user.email],
            cc=funder.cc_emails.values_list("email", flat=True),
        )
        if can_send_email():
            email.send()

    def notify_requester_from_funders(self):
        """Send automated email to requester from all selected funders"""
        for funder in self.applied_funders.all():
            if funder.send_email_template:
                subject = funder.email_subject
                message = funder.email_template
                email = EmailMessage(
                    subject=subject,
                    body=message,
                    from_email=funder.user.username + "@penncfa.com",
                    to=[self.requester.user.email],
                )
                if can_send_email():
                    email.send()

    def notify_requester(self, grants):
        """Notify a requester that an event has been funded."""
        context = {"event": self, "grants": grants}
        subject = render_to_string(
            "app/grant_email_subject.txt", context=context
        ).strip()
        message = render_to_string("app/grant_email.txt", context=context)
        if can_send_email():
            self.requester.user.email_user(subject, message)

    def notify_requester_for_followups(self):
        """
        Notify a requester that his event is over
        and he needs to answer followup questions
        """

penncfa/templates/app/templatetags/application.html
{% load widgets %}

{% if event.followup_needed or event.over %}
<section id="followup" class="short-answer">
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Followup Questions
      <small>
        post-event report
      </small>
    </h2>
  </div>
  <div class="section-content">
    <fieldset>
    {% for qa in followup_qas %}
    <label for="followupquestion_{{qa.question.id}}">{{ qa.question.question }}</label>
    <textarea type="text"
      id="followupquestion_{{qa.question.id}}"
      name="followupquestion_{{qa.question.id}}"
      class="span8 followupquestion form-control"
      {{extra_attrs}}>{{qa.answer.answer}}</textarea>
    {% endfor %}
    {% for qa in commonfollowup_qas %}
    <label for="commonfollowupquestion_{{qa.question.id}}">{{ qa.question.question }}</label>
    <textarea type="text"
      id="commonfollowupquestion_{{qa.question.id}}"
      name="commonfollowupquestion_{{qa.question.id}}"
      class="span8 commonfollowupquestion form-control"
      {{extra_attrs}}>{{qa.answer.answer}}</textarea>
    {% endfor %}
    </fieldset>
  </div>
</section>
{% endif %}

{% event_details %}

<section id="eligibility">
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Eligibility Questions
      <small>select if applicable</small>
    </h2>
  </div>
  <div class="section-content">
    <fieldset>
      {% for qa in eligibility_qas %}
        {% if not readonly or qa.answer.answer %}
        <div class="form-group">
          <label id="eligibilitylabel_{{qa.question.id}}"
                 class="control-label">
            Question {{forloop.counter}}</label>
          <div class="controls">
            <label>
              <input type="checkbox"
                     id="eligibilityquestion_{{qa.question.id}}"
                     name="eligibilityquestion_{{qa.question.id}}"
                     data-required-funder-ids="{{qa.question.required_funder_ids}}"
                     {% if event.funded %}
                     class="bool-q disable" readonly
                     {% else %}
                     class="bool-q"
                     {% endif %}
                     data-qid="{{qa.question.id}}"
                     {{extra_attrs}} {{event_over_disable}}
                     {% if qa.answer.answer %}checked{% endif %}>
              {{ qa.question.question }}</label>
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </fieldset>
  </div>
</section>

<section class="short-answer">
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>Free-Response Questions</h2>
  </div>
  <div class="section-content">
    <fieldset>
      {% for qa in commonfreeresponse_qas %}
      <label for="commonfreeresponsequestion_{{qa.question.id}}">{{ qa.question.question }}</label>
      <textarea type="text"
        id="commonfreeresponsequestion_{{qa.question.id}}"
        name="commonfreeresponsequestion_{{qa.question.id}}"
        class="span8 commonfreeresponsequestion form-control"
        {{extra_attrs}} {{event_over_disable}}
        {% if event.funded %}readonly{% endif %}>{{qa.answer.answer}}</textarea>
      {% endfor %}
    </fieldset>
  </div>
</section>

<section>
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Items
      <small>list line items for funding</small>
    </h2>
  </div>
  {% if not readonly %}
  <div class="section-content">
    <div class="alert alert-info d-print-none">
      <strong>Heads up!</strong>
      If you are importing line items from a CSV or Excel file, make sure that your sheet contains the same column names as our online form. Additionally, make sure each category is a valid category in the selection dropdown.
    </div>
  </div>
  {% endif %}
  <div class="section-content">
    <fieldset>
      {% if not user.is_staff and user.profile.is_requester %}
      {% itemlist_requester 0 event.item_set.all event.funded %}
      {% itemlist_requester 1 event.item_set.all event.funded %}
      {% else %}
      {% itemlist_funder 0 event.item_set.all event.applied_funders.all user.profile.id %}
      {% itemlist_funder 1 event.item_set.all event.applied_funders.all user.profile.id %}
      {% endif %}
      <table class="items-total">
        <tr>
          <td>Expense Total</td>
          <td>$<span class="items-exp-total">0.00</span></td>
        </tr>
        {% if user.is_staff or not user.profile.is_requester %}
        <tr>
          <td>Funding Received Total</td>
          <td>&ndash;$<span class="items-recv-total">0.00</span></td>
        </tr>
        {% endif %}
        <tr>
          <td>Additional Funds Total</td>
          <td>&ndash;$<span class="items-rev-total">0.00</span></td>
        </tr>
        <tr>
          <td>Final Total</td>
          <td>$<span class="items-final-total">0.00</span></td>
        </tr>
      </table>
    </fieldset>
  </div>
</section>

<section>
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Funders
      <small>select to apply</small>
    </h2>
  </div>
  <div class="section-content">
    <fieldset>
    {% for funder in funders %}
      {% if not readonly or funder in event.applied_funders.all %}
      <div class="funder-check">
        <label class="checkbox">
          <input
            id="funder-checkbox-{{funder.id}}"
            data-funderid="{{funder.id}}"
            data-required-question-ids="{{funder.required_eligibility_question_ids}}"
            name="funder_{{ funder.id }}"
            class="funder-checkbox"
            {% if funder in event.applied_funders.all %}checked{% endif %}
            type="checkbox" {{extra_attrs}} {{event_over_disable}}>
            {{funder}}
        </label>
        <span class="text-secondary">(<a href="mailto:{{funder.osa_email}}">{{funder.osa_email}}</a>)</span>
        <p class="help-block">{{funder.mission_statement}}</p>
      </div>
      {% endif %}
    {% endfor %}
    </fieldset>
    <!-- template for the recommendation label -->
    <script id="recommended-label" type="text/template">
      <span class="label label-success recommended-label">Recommended</span>
    </script>
  </div>
</section>

<section class="short-answer">
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Extra Questions
      <small>specific to each funder</small>
    </h2>
  </div>
  <div class="section-content">
    <fieldset>
    <p id="funder-no-q">
      {% if not user.is_staff and user.profile.is_requester %}
      No questions yet. Please select funders.
      {% else %}
      No other questions answered.
      {% endif %}
    </p>
    {% for qa in funder_qas %}
      {% if not readonly or qa.question.funder == user.profile or qa.question.funder == event.shared_funder %}
      <div class="extra-answer funder-q-{{ qa.question.funder.id }}">
        <label>{{ qa.question.question }} <em>for {{ qa.question.funder }}</em></label>
        <textarea type="text"
          name="freeresponsequestion_{{qa.question.id}}"
          class="span8 form-control"
          {{extra_attrs}} {{event_over_disable}}>{{qa.answer.answer}}</textarea>
      </div>
      {% endif %}
    {% endfor %}
    </fieldset>
  </div>
</section>

<section>
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Comments
      <small>
        {% if user.profile.is_funder %}
        feel free to leave a message
        {% else %}
        here are some comments from your potential funders
        {% endif %}
      </small>
    </h2>
  </div>
  <div class="section-content">
    {% for comment in event.comments %}
    <p><strong>{{ comment.funder }}</strong> wrote on {{ comment.created }}</p>
    <blockquote>{{ comment }}</blockquote>
    {% empty %}
    There are no comments yet.
    {% endfor %}
    {% if user == event.requester.user or user.profile.is_funder %}
    {% if user and user.profile.is_funder %}
    <p>Specify any conditions and stipulations here.</p>
    {% else %}
    <p>Leave a comment for your funder here.</p>
    {% endif %}
    <textarea name="new-comment" class="span8 form-control"></textarea> 
    {% endif %}
  </div>
</section>

penncfa/templates/app/templatetags/event-details-form.html
<section>
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      Event
      <small>details about the event</small>
    </h2>
  </div>
  <div class="section-content">
    <div class="alert alert-info">
      <strong>Heads up!</strong>
      Make sure you fill out all fields before submitting the application.
    </div>
    <div class="django-form clearfix">
        {{ form.as_p }}
    </div>
  </div>
</section>

penncfa/templates/app/templatetags/event-details-show.html
<section>
  <div class="section-header">
    <a class='section-toggle'></a>
    <h2>
      {{event.name}}
    <small>details about the event</small>
    </h2>
    {% if event.has_update %}
    <h4><small>Last updated: {{ event.updated_at }}</small></h4>
    {% endif %}
    <h4><small>Date submitted: {{ event.created_at }}</small></h4>
  </div>
  <div class="section-content">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="id_name" class="control-label">Event Name</label>
          <div class="controls">
            <input value="{{ event.name }}" type="text" name="name" id="id_name" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_date" class="control-label">Event Date</label>
          <div class="controls">
            <input value="{{ event.date|date:'Y-m-d' }}" {% if event %}data-edit="true"{% endif %} data-year="{{ event.date.year }}" data-month="{{ event.date.month }}" data-day="{{ event.date.day }}" type="text" name='date' id="id_date" class="form-control datepicker" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_time" class="control-label">Event Time</label>
          <div class="controls">
            <input value="{{ event.time|date:'H:i' }}" type="time" name="time" id="id_time" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_organizations" class="control-label">Organization(s)</label>
          <div class="controls">
            <input value="{{ event.organizations }}" type="text" name="organizations" id="id_organizations" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_location" class="control-label">Location</label>
          <div class="controls">
            <input value="{{ event.location }}" name="location" type="text" id="id_location" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_anticipatedattendance" class="control-label">Anticipated Attendance</label>
          <div class="controls">
            <input value="{{ event.anticipated_attendance }}" type="number" min="0" name="anticipatedattendance" id="id_anticipatedattendance" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="id_contactname" class="control-label">Contact Name</label>
          <div class="controls">
            <input value="{{ event.contact_name }}" type="text" name="contactname" id="id_contactname" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_contactemail" class="control-label">Contact Email</label>
          <div class="controls">
            <input value="{{ event.contact_email }}" type="email" name="contactemail" id="id_contactemail" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_contactphone" class="control-label">Contact Phone</label>
          <div class="controls">
            <input value="{{ event.contact_phone }}" type="text" name="contactphone" id="id_contactphone" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_advisoremail" class="control-label">Advisor Email</label>
          <div class="controls">
            <input value="{{ event.advisor_email }}" type="email" name="advisoremail" id="id_advisoremail" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="id_advisorphone" class="control-label">Advisor Phone</label>
          <div class="controls">
            <input value="{{ event.advisor_phone }}" type="text" name="advisorphone" id="id_advisorphone" class="form-control" {{extra_attrs}} {{event_over_disable}}>
          </div>
        </div>
        <div class="form-group">
          <label for="fundingalreadyreceived" class="control-label">Funding Already Receieved</label>
          <div class="controls">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">$</span>
              </div>
              <input value="{{ event.funding_already_received }}" type="number" min="0" name='fundingalreadyreceived' id="fundingalreadyreceived" class="form-control" {{extra_attrs}} {{event_over_disable}}>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

penncfa/templates/app/templatetags/itemlist-funder.html
{% if is_revenue %}
<div>
  <h3>
    Additional Funds
    <small>list all non-CFA funding sources and admission fees</small>
  </h3>
</div>
{% else %}
<div>
  <h3>
    Expense Items
    <small>list your projected expense items</small>
  </h3>
</div> 
{% endif %}
<table class='table table-striped' id='item-table'>
  <thead>
    {% if items_data %}
    <tr>
      {% for title in titles %}
      <th>{{ title }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for item, grant_datas in items_data %}
    <tr class='{% if is_revenue %} revenue-item {% else %} expense-item {% endif %}'>
      <td>{{ item.name }}</td>
      <td>{{ item.get_category_display }}</td>
      <td>{{ item.quantity }}</td>
      <td>${{ item.price_per_unit }}</td>
      <td>
        $<span class="item-amount">{{item.total}}</span>
      </td>

      {% if not is_revenue %}
      <td>
        $<span class="item-received">{{ item.total_received }}</span>
      </td>
      {% endif %}

      {% for funder_id, grant_amount, item_id in grant_datas %}
      {% if funder_id == current_funder %}
        <td style="min-width:125px">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
            <input class="funding-given form-control" name="item_{{ item_id }}"
              type='text'
              {% if grant_amount is not None %}
              value="{{ grant_amount }}"
              {% endif %}
              pattern="^(?!Fund Amount\.\.\.)^\d*(\.\d{2}$)?"
          </div>
        </td>
      {% else %}
        {% if grant_amount is not None %}
          <td>${{ grant_amount }}</td>
          {% else %}
          <td><em>pending</em></td>
        {% endif %}
      {% endif %}
      {% endfor %}
    </tr>
    {% endfor %}
    {% else %}
    No items have been added.
    {% endif %}
  </tbody>
</table>